version: "3.9"

services:

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    expose:
      - "5432"
    # ports:
    #   - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@auth-db:5432/auth_db
      JWT_SECRET: super_secret_key
    depends_on:
      - auth-db

  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_db
    expose:
      - "5432"
    # ports:
    #   - "5434:5432"
    volumes:
      - account-db_data:/var/lib/postgresql/data

  account-service:
    build: ./account-service
    container_name: account-service
    expose:
      - "8081"
    # ports:
    #   - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:password@account-db:5432/account_db
      JWT_SECRET: super_secret_key
    depends_on:
      - account-db
      
  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    expose:
      - "5432"
    # ports:
    #   - "5435:5432"
    volumes:
      - payment-db_data:/var/lib/postgresql/data

  payment-service:
    build: ./payment-service
    container_name: payment-service
    expose:
      - "8082"
    # ports:
    #   - "8082:8082"
    environment:
      DATABASE_URL: postgres://postgres:password@payment-db:5432/payment_db
      JWT_SECRET: super_secret_key
    depends_on:
      - payment-db

  ledger-db:
    image: postgres:15
    container_name: ledger-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ledger_db
    expose:
      - "5432"
    # ports:
    #   - "5436:5432"
    volumes:
          - ledger-db_data:/var/lib/postgresql/data

  ledger-service:
    build: ./ledger-service
    container_name: ledger-service
    expose:
      - "8083"
    # ports:
    #   - "8083:8083"
    environment:
      DATABASE_URL: postgres://postgres:password@ledger-db:5432/ledger_db
      JWT_SECRET: super_secret_key
    depends_on:
      - ledger-db

  audit-db:
    image: postgres:15
    container_name: audit-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audit_db
    expose:
      - "5432"
    # ports:
    #   - "5437:5432"
    volumes:
      - audit-db_data:/var/lib/postgresql/data

  audit-service:
    build: ./audit-service
    container_name: audit-service
    expose:
      - "8084"
    environment:
      DATABASE_URL: postgres://postgres:password@audit-db:5432/audit_db
    depends_on:
      - audit-db

  saga-orchestrator:
    build: ./saga-orchestrator
    container_name: saga-orchestrator
    ports:
      - "8085:8085"
    environment:
      PAYMENT_URL: http://payment-service:8082
      ACCOUNT_URL: http://account-service:8081
      LEDGER_URL: http://ledger-service:8083
      AUDIT_URL: http://audit-service:8084
    depends_on:
      - payment-service
      - account-service
      - ledger-service
      - audit-service

volumes:
  auth_db_data:
  account-db_data:
  payment-db_data:
  ledger-db_data:
  audit-db_data: