version: "3.9"

services:

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@auth-db:5432/auth_db
      JWT_SECRET: super_secret_key
    depends_on:
      - auth-db

  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_db
    ports:
      - "5434:5432"
    volumes:
      - account-db_data:/var/lib/postgresql/data

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:password@account-db:5432/account_db
      JWT_SECRET: super_secret_key
    depends_on:
      - account-db
      
  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    ports:
      - "5435:5432"
    volumes:
      - payment-db_data:/var/lib/postgresql/data

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: postgres://postgres:password@payment-db:5432/payment_db
      JWT_SECRET: super_secret_key
    depends_on:
      - payment-db

  ledger-db:
    image: postgres:15
    container_name: ledger-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ledger_db
    ports:
      - "5436:5432"
    volumes:
          - ledger-db_data:/var/lib/postgresql/data

  ledger-service:
    build: ./ledger-service
    container_name: ledger-service
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: postgres://postgres:password@ledger-db:5432/ledger_db
      JWT_SECRET: super_secret_key
    depends_on:
      - ledger-db
volumes:
  auth_db_data:
  account-db_data:
  payment-db_data:
  ledger-db_data: